"""
Reservoir Release Optimizer — Streamlit UI
Run with: streamlit run app.py
"""
import datetime
import os
import tempfile
import time

import numpy as np
import pandas as pd
import streamlit as st

from reservoir_optimization_v4 import (
    PRICES,
    ReservoirV4,
    find_windows,
    get_midnight_index,
    load_data,
    load_evaporation,
    load_realpaver_solution,
    optimize,
)

# ── Page config ────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Reservoir Release Optimizer",
    page_icon="💧",
    layout="wide",
)

OBJECTIVE_LABELS = {
    'revenue':        'Maximize Revenue ($)',
    'power':          'Maximize Power Generation (MWh)',
    'target_release': 'Meet a Target Water Release (TCM)',
    'min_release':    'Minimize Water Release (Conservation)',
}

METHOD_DESCRIPTIONS = {
    'baseline':  'Simple — doubles penalty every 2,000 steps if infeasible. Fast but may overshoot.',
    'adaptive':  'Adjusts penalty based on how fast violations shrink. Good general-purpose choice.',
    'learnable': 'Tracks the rate of change of violations over time. Slowest but most robust.',
}

PENALTY_DESCRIPTIONS = {
    'L1': 'Penalizes the sum of violations. Faster convergence, less smooth.',
    'L2': 'Penalizes the sum of squared violations. Smoother gradient, may find better solutions.',
}

DEFAULT_HYDRO = os.path.join('data', 'hydropower_hourly.csv')
DEFAULT_EVAP  = os.path.join('data', 'hourly_evaporation_empirical_overwater_updated.csv')


def _do_load(hydro, evap):
    data       = load_data(hydro)
    evap_dict  = load_evaporation(evap)
    windows    = find_windows(data, n_windows=10)
    date_index = get_midnight_index(data)   # compute once, store alongside data
    st.session_state.update(
        data=data, evap_dict=evap_dict, windows=windows,
        date_index=date_index, result=None,
    )


# ── Auto-load if default files exist ───────────────────────────────────────
if 'data' not in st.session_state:
    if os.path.exists(DEFAULT_HYDRO) and os.path.exists(DEFAULT_EVAP):
        with st.spinner("Loading data from data/ folder…"):
            _do_load(DEFAULT_HYDRO, DEFAULT_EVAP)

# ── Header ─────────────────────────────────────────────────────────────────
st.title("💧 Reservoir Release Optimizer")
st.caption(
    "Find the optimal hourly water release schedule for a 24-hour planning window. "
    "Select an objective, configure constraints, and download the resulting schedule."
)

# ── Sidebar ─────────────────────────────────────────────────────────────────
with st.sidebar:
    # ── Data Files ──────────────────────────────────────────────────────────
    st.header("Data Files")
    hydro_path = st.text_input("Hydropower CSV", value=DEFAULT_HYDRO)
    evap_path  = st.text_input("Evaporation CSV", value=DEFAULT_EVAP)

    if st.button("Load Data", type="primary", use_container_width=True):
        try:
            with st.spinner("Loading data..."):
                _do_load(hydro_path, evap_path)
            st.success(f"Loaded {len(st.session_state['data']):,} records · "
                       f"{len(st.session_state['windows'])} recommended windows")
        except FileNotFoundError as exc:
            st.error(f"File not found: {exc}")
        except Exception as exc:
            st.error(f"Error: {exc}")

    if 'data' in st.session_state:
        st.caption(f"{len(st.session_state['data']):,} hourly records loaded")

    st.divider()

    # ── RealPaver Warm Start ─────────────────────────────────────────────
    with st.expander("RealPaver Warm Start"):
        st.caption(
            "RealPaver is an interval constraint solver that finds a guaranteed-feasible "
            "starting point for the optimizer. Upload the output file from a RealPaver run "
            "to use it as a warm start. This can improve feasibility when the optimizer "
            "struggles to satisfy all constraints on its own."
        )
        rp_file = st.file_uploader(
            "Upload RealPaver results (.txt)",
            type=["txt"],
            help="Upload the output file produced by running RealPaver on the constraint file "
                 "generated by generate_realpaver.py. The file should contain OUTER BOX sections.",
        )
        if rp_file is not None:
            try:
                raw = rp_file.getvalue()
                # Save to temp file so load_realpaver_solution can open it
                with tempfile.NamedTemporaryFile(
                    mode='wb', suffix='.txt', delete=False
                ) as tmp:
                    tmp.write(raw)
                    tmp_path = tmp.name
                rp_Q = load_realpaver_solution(tmp_path)
                os.unlink(tmp_path)
                st.session_state['rp_Q'] = rp_Q
                st.success(f"Parsed {len(rp_Q)} hourly values from RealPaver output.")
                st.caption(
                    "⚠️ RealPaver results are specific to the window they were generated for. "
                    "Make sure this file matches the time window you select below."
                )
            except Exception as exc:
                st.error(f"Could not parse RealPaver file: {exc}")
                st.session_state.pop('rp_Q', None)
        elif 'rp_Q' in st.session_state:
            st.info("RealPaver warm start loaded from previous upload.")

# ── Guard: require loaded data ─────────────────────────────────────────────
if 'data' not in st.session_state:
    st.info("👈 Load your data files using the sidebar to get started.")
    st.stop()

data      = st.session_state['data']
evap_dict = st.session_state['evap_dict']
windows   = st.session_state['windows']

# ── Configure Run ──────────────────────────────────────────────────────────
st.header("Configure Run")

# ── Window + Objective ─────────────────────────────────────────────────────
col_win, col_obj = st.columns(2)

with col_win:
    st.subheader("Time Window")
    win_mode = st.radio(
        "Selection method",
        ["Recommended windows", "Pick any date"],
        horizontal=True,
        help=(
            "Recommended windows are pre-filtered periods where the reservoir was actively "
            "generating power (>200 MWh) and had significant discharge (>20 m³/s). "
            "'Pick any date' lets you choose any 24-hour period in the dataset."
        ),
    )

    if win_mode == "Recommended windows":
        window_labels = [
            f"{data[s]['time']}  (window {i+1})" for i, s in enumerate(windows)
        ]
        window_choice = st.selectbox("Time window (24-hour period)", window_labels)
        window_idx    = window_labels.index(window_choice)
        start_idx     = windows[window_idx]
        window_label  = window_choice
    else:
        date_index = st.session_state.get('date_index', {})
        if not date_index:
            st.error("No midnight records found in the dataset.")
            st.stop()
        min_date = min(date_index.keys())
        max_date = max(date_index.keys())
        chosen_date = st.date_input(
            "Select date",
            min_value=min_date,
            max_value=max_date,
            value=min_date,
        )
        if chosen_date in date_index:
            start_idx    = date_index[chosen_date]
            window_label = str(chosen_date)
        else:
            nearest   = min(date_index.keys(), key=lambda d: abs((d - chosen_date).days))
            start_idx = date_index[nearest]
            window_label = str(nearest)
            st.warning(
                f"No data starts at midnight on {chosen_date}. "
                f"Using nearest available date: {nearest}."
            )
        # Warn if this is a low-activity period
        gen_check = sum(data[start_idx + t]['power'] for t in range(24))
        if gen_check < 50:
            st.warning(
                f"Low power generation for this period ({gen_check:.0f} MWh). "
                "The optimizer may find a trivial solution."
            )

with col_obj:
    st.subheader("Optimization Objective")
    objective_mode = st.radio(
        "What to optimize",
        options=list(OBJECTIVE_LABELS.keys()),
        format_func=lambda k: OBJECTIVE_LABELS[k],
    )

target_release_tcm = None
if objective_mode == 'target_release':
    preview            = ReservoirV4(data, start_idx, evap_dict)
    target_release_tcm = st.number_input(
        "Target total release over 24 hours (TCM)",
        min_value=100.0,
        max_value=30000.0,
        value=float(round(preview.demand_target / 100) * 100),
        step=100.0,
        help=f"Historical release for this window: {preview.demand_target:.0f} TCM. "
             f"Max turbine capacity is ~23,500 TCM/day at 273 m³/s.",
    )

# ── Electricity Prices ─────────────────────────────────────────────────────
with st.expander("Electricity Prices ($/MWh)"):
    price_mode = st.radio(
        "Price source",
        ["Default (ERCOT-style)", "Flat rate", "Custom (24-hour)", "Upload CSV"],
        horizontal=True,
        help="Sets the hourly electricity price used when computing revenue.",
    )

    if price_mode == "Default (ERCOT-style)":
        custom_prices = PRICES.tolist()
        st.caption(
            "Typical day-ahead prices: low overnight (~$20–25/MWh), "
            "rising through the morning, peak in late afternoon (~$85/MWh at 5pm)."
        )

    elif price_mode == "Flat rate":
        flat_price    = st.number_input("Price ($/MWh)", 0.0, 500.0, 50.0, 1.0)
        custom_prices = [flat_price] * 24

    elif price_mode == "Custom (24-hour)":
        st.caption("Enter the price for each hour of the day (hour 0 = midnight).")
        cols_p = st.columns(6)
        custom_prices = []
        for h in range(24):
            with cols_p[h % 6]:
                p = st.number_input(
                    f"Hr {h:02d}", 0.0, 500.0, float(PRICES[h]), 1.0,
                    key=f"price_{h}",
                )
                custom_prices.append(p)

    elif price_mode == "Upload CSV":
        st.caption(
            "Upload a CSV with 24 price values (one per row, or all in one row). "
            "No header needed."
        )
        price_file = st.file_uploader("Price CSV", type=["csv"], key="price_upload")
        if price_file:
            try:
                price_df      = pd.read_csv(price_file, header=None)
                custom_prices = price_df.values.flatten()[:24].tolist()
                if len(custom_prices) < 24:
                    st.error(f"Need 24 prices, got {len(custom_prices)}.")
                    custom_prices = PRICES.tolist()
                else:
                    st.success(f"Loaded 24 hourly prices.")
            except Exception as exc:
                st.error(f"Error reading price file: {exc}")
                custom_prices = PRICES.tolist()
        else:
            custom_prices = PRICES.tolist()

    # Price chart preview
    price_chart_df = pd.DataFrame({
        'Hour':          [f"{h:02d}:00" for h in range(24)],
        'Price ($/MWh)': custom_prices,
    }).set_index('Hour')
    st.bar_chart(price_chart_df, height=180)

# ── Advanced Settings ──────────────────────────────────────────────────────
with st.expander("Advanced Settings"):
    st.write("**Physical constraints**")

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        q_min = st.number_input(
            "Release minimum (m³/s)", min_value=0.0, max_value=50.0,
            value=2.0, step=0.5,
            help="Environmental flow — the minimum discharge required every hour.",
        )
    with c2:
        q_max = st.number_input(
            "Release maximum (m³/s)", min_value=50.0, max_value=500.0,
            value=273.0, step=1.0,
            help="Turbine capacity — the maximum discharge allowed per hour.",
        )
    with c3:
        level_band = st.slider(
            "Level band (±m)", 0.5, 5.0, 1.5, 0.1,
            help="Reservoir level must stay within this range of the starting level.",
        )
    with c4:
        ramp_max = st.slider(
            "Max ramp rate (m³/s / hr)", 10, 100, 40, 5,
            help="Maximum allowed change in discharge between consecutive hours.",
        )

    c5, c6, c7 = st.columns(3)
    with c5:
        s_end_tol = st.number_input(
            "End storage tolerance (TCM)", min_value=100.0, max_value=20000.0,
            value=2000.0, step=100.0,
            help="End-of-day reservoir storage must finish within this amount of the starting storage.",
        )
    with c6:
        demand_tol_pct = st.slider(
            "Demand tolerance (%)", 5, 50, 20, 5,
            help="Allowed deviation from the historical daily release target.",
        )
    with c7:
        min_gen_pct = st.slider(
            "Min generation (% of historical)", 0, 100, 50, 5,
            help="Total power generated must be at least this percentage of the historical output for the window.",
        )

    st.divider()
    st.write("**Optimizer settings**")
    adv_opt1, adv_opt2 = st.columns(2)

    with adv_opt1:
        method = st.radio(
            "Penalty update method",
            options=['adaptive', 'learnable', 'baseline'],
            format_func=lambda m: m.capitalize(),
            help="\n\n".join(f"**{k.capitalize()}**: {v}" for k, v in METHOD_DESCRIPTIONS.items()),
        )
        st.caption(METHOD_DESCRIPTIONS[method])

    with adv_opt2:
        ptype = st.radio(
            "Penalty type",
            options=['L1', 'L2'],
            help="\n\n".join(f"**{k}**: {v}" for k, v in PENALTY_DESCRIPTIONS.items()),
        )
        st.caption(PENALTY_DESCRIPTIONS[ptype])

# ── Run button ─────────────────────────────────────────────────────────────
init_Q = st.session_state.get('rp_Q', None)
if init_Q is not None:
    st.info(
        "RealPaver warm start is active — the optimizer will start from the "
        "RealPaver feasible point instead of historical data."
    )

if st.button("▶ Run Optimization", type="primary", use_container_width=True):
    label = OBJECTIVE_LABELS[objective_mode]
    with st.spinner(f"Optimizing ({label}) using {method} / {ptype}… ~30 seconds"):
        np.random.seed(42)
        model = ReservoirV4(
            data, start_idx, evap_dict,
            objective_mode=objective_mode,
            target_release_tcm=target_release_tcm,
            level_band=level_band,
            ramp_max=ramp_max,
            demand_tol_pct=demand_tol_pct / 100.0,
            prices=custom_prices,
            q_min=q_min,
            q_max=q_max,
            s_end_tol=s_end_tol,
            min_gen_pct=min_gen_pct / 100.0,
        )
        t0      = time.time()
        oQ      = optimize(model, method=method, ptype=ptype,
                           max_iters=8000, init_Q=init_Q)
        elapsed = time.time() - t0

    st.session_state['result'] = dict(
        model=model, oQ=oQ, elapsed=elapsed,
        objective_mode=objective_mode,
        window_label=window_label,
        target_release_tcm=target_release_tcm,
        method=method, ptype=ptype,
        used_realpaver=init_Q is not None,
    )

# ── Results ────────────────────────────────────────────────────────────────
if not st.session_state.get('result'):
    st.stop()

r     = st.session_state['result']
model = r['model']
oQ    = r['oQ']

oP, oL, _ = model.compute_power(oQ)
aP, aL, _ = model.compute_power(model.actual_Q)

feas  = model.is_feasible(oQ)
viol  = model.total_violation(oQ)
ns, nt = model.n_constraints_satisfied(oQ)

actual_revenue = model.revenue(model.actual_Q)
opt_revenue    = model.revenue(oQ)
actual_tcm     = model.total_release_tcm(model.actual_Q)
opt_tcm        = model.total_release_tcm(oQ)
actual_mwh     = float(np.sum(aP))
opt_mwh        = float(np.sum(oP))

st.divider()
st.header(f"Results — {r['window_label']}")

rp_tag     = " · RealPaver warm start" if r['used_realpaver'] else ""
status_str = "✅ Feasible" if feas else "⚠️ Infeasible"
st.caption(
    f"Objective: **{OBJECTIVE_LABELS[r['objective_mode']]}**  ·  "
    f"Method: **{r['method'].capitalize()} / {r['ptype']}**  ·  "
    f"Solved in {r['elapsed']:.1f}s  ·  "
    f"{status_str} ({ns}/{nt} constraints){rp_tag}"
)

if not feas:
    st.warning(
        f"The solution violates some constraints (total violation: {viol:.2f}). "
        "Try relaxing the Advanced Settings or switching to the Learnable method."
    )

if r['objective_mode'] == 'target_release' and r['target_release_tcm']:
    deviation = abs(opt_tcm - r['target_release_tcm'])
    st.info(
        f"**Target release:** {r['target_release_tcm']:,.0f} TCM  ·  "
        f"**Achieved:** {opt_tcm:,.0f} TCM  ·  "
        f"**Deviation:** {deviation:,.0f} TCM"
    )

# Summary metric cards
m1, m2, m3, m4 = st.columns(4)
m1.metric(
    "Revenue",
    f"${opt_revenue:,.0f}",
    delta=f"${opt_revenue - actual_revenue:+,.0f} vs actual",
)
m2.metric(
    "Total Release",
    f"{opt_tcm:,.0f} TCM",
    delta=f"{opt_tcm - actual_tcm:+,.0f} vs actual",
    delta_color="inverse",
)
m3.metric(
    "Power Generated",
    f"{opt_mwh:,.1f} MWh",
    delta=f"{opt_mwh - actual_mwh:+,.1f} vs actual",
)
m4.metric(
    "Constraints",
    f"{ns} / {nt}",
    delta="Feasible" if feas else "Infeasible",
    delta_color="normal" if feas else "inverse",
)

# Hourly schedule table
st.subheader("Hourly Schedule")
rows = []
for t in range(model.horizon):
    ramp = float(oQ[t] - oQ[t - 1]) if t > 0 else 0.0
    rows.append({
        'Hour':                   t,
        'Price ($/MWh)':          model.prices[t],
        'Actual Release (m³/s)':  round(float(model.actual_Q[t]), 1),
        'Optimal Release (m³/s)': round(float(oQ[t]), 1),
        'Actual Power (MW)':      round(float(aP[t]), 1),
        'Optimal Power (MW)':     round(float(oP[t]), 1),
        'Water Level (m)':        round(float(oL[t]), 3),
        'Evaporation (m³/s)':     round(float(model.evap[t]), 2),
        'Ramp (m³/s)':            round(ramp, 1),
        'Hourly Revenue ($)':     round(float(model.prices[t] * oP[t]), 0),
    })

df = pd.DataFrame(rows)
st.dataframe(df, use_container_width=True, hide_index=True)

safe_label = (
    r['window_label']
    .replace('/', '-').replace(':', '_').replace(' ', '_')
    .replace('(', '').replace(')', '')
)
st.download_button(
    "⬇ Download Schedule as CSV",
    data=df.to_csv(index=False).encode(),
    file_name=f"schedule_{safe_label}.csv",
    mime="text/csv",
)

# Constraint details
with st.expander("Constraint Details"):
    cc1, cc2 = st.columns(2)
    with cc1:
        st.write("**Physical limits**")
        st.write(f"- Release bounds: {model.Q_min} – {model.Q_max} m³/s")
        st.write(f"- Level band: {model.L_min:.2f} – {model.L_max:.2f} m")
        st.write(f"- Ramp rate: ±{model.ramp_max} m³/s / hr")
    with cc2:
        st.write("**Operational targets**")
        st.write(f"- Daily release: {model.demand_target:.0f} ± {model.demand_tolerance:.0f} TCM")
        st.write(f"- End storage tolerance: ±{model.S_end_tol:.0f} TCM")
        st.write(f"- Min generation: {model.min_gen:.0f} MWh")
    st.write(
        f"**Evaporation** — avg {np.mean(model.evap):.2f} m³/s, "
        f"daily loss {np.sum(model.evap) * model.dt / 1000:.0f} TCM"
    )
